wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/bacio.c
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/baciof.f	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/baciof.h	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/bafrio.f	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/byteswap.c	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/chk_endianc.f	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/clib.h	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/compilation_list.log	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/compile-intel-hswl.log	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/fast-byteswap.h	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/makebacio_ccs.sh	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/makebacio_cray.sh	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/makebacio_cray_cray.sh	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/makebacio_theia.sh	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/makebacio_wcoss.sh	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/makebacio_wcoss2.sh	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/makebacio_zeus.sh	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/modulefile_test_cray	
wget http://www.nco.ncep.noaa.gov/pmb/codes/nwprod/lib/bacio/v2.0.2/src/modulefile_test_intel	

