#
#  $Author: tomita $
#  $Date: 2007/08/01 20:09:58 $
#  $Revision: 1.1.1.1 $
#
EXEC=PorceClayMaskIBISClima

OBJS = 	PorceClayMaskIBISClima.o

$(EXEC):	$(OBJS)
	$(F90) -o $(EXEC) $(F90FLAG) $(LOADFLAG) $(OBJS)

PorceClayMaskIBISClima.o: 	PorceClayMaskIBISClima.f90
	$(F90) -c $(F90FLAG) PorceClayMaskIBISClima.f90

clean:
	-rm -f $(OBJS)
	-rm -f $(OBJS_CC)
	-rm -f $(EXEC)
	-rm -f *.mod

.F90.o :
	$(F90) $(F90FLAG) -c  $<

.f90.o:
	$(F90) $(F90FLAG) -c $< 
.c.o:
	$(CC) $(CFLAGS) $(DEFS) -c $< 
