#
#  $Author: pkubota $
#  $Date: 2007/10/10 20:24:23 $
#  $Revision: 1.1 $
#
# $Id: Makefile.linux64,v 1.1 2007/10/10 20:24:23 pkubota Exp $
#
#
#  PC Cluster, mpi scali
#
FTRACE= 
OPENMP= -fopenmp
F90=ftn -ffast-math -fconvert=big-endian  -ffree-line-length-none -ffast-math -funroll-loops -ftree-vectorizer-verbose=2  ${OPENMP} 
NOASSUME=
HVECTOR=
INLINE_CU_GRELL=
INLINE_CU_KUO=
INLINE_CU_RAS=
INLINE_SOUZA=
LOADFLAG= 
include Makefile.common
